language: node_js
node_js:
  - "8"
install:
  - npm install
env:
  - DDIR=deployment-dir
script:
  - mkdir -p $RESOURCEROOT
  - node ./scripts/generate_orcid_file.js
  - echo "fix tests then add 'npm run test' here"
before_deploy:
  - zip -r $TRAVIS_COMMIT $(git ls-files)
  - mkdir -p $DDIR
  - cp $TRAVIS_COMMIT.zip $DDIR
deploy:
  - provider: s3
    skip-cleanup: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: $AWS_BUCKET
    region: $AWS_REGION
    local-dir: $DDIR
    upload-dir: "back/$TRAVIS_BRANCH"
    on:
      branch: development
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: $AWS_APP_NAME
    deployment_group: $AWS_DEPLOYMENT_GROUP
    region: $AWS_REGION
    bucket: $AWS_BUCKET
    key: "back/$TRAVIS_BRANCH/$TRAVIS_COMMIT.zip"
    wait-until-deployed: true
    on:
      branch: development

