#!/bin/bash

# Don't actually deploy yet (commented out)

# source /home/ec2-user/db_env_vars
# export NODE_ENV=production
# export RESOURCEROOT=/home/ec2-user/resources

cd /home/ec2-user/codedeploy-back-landingpad/
# npm install
# npm run migrate
# npm run exec knex seed:run

# Replace the old deployment files with the new ones
# rm -rf /home/ec2-user/deployments/toastdos-back
# cp -r /home/ec2-user/codedeploy-back-landingpad/ /home/ec2-user/deployments/toastdos-back

# Restart the service
# sudo /usr/bin/systemctl restart toastdos-back


